// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8_Cko7i4Aj4P_51oXqCmVqMvX3J2ENyE',
    appId: '1:904029642955:web:13dc8c54541b5dc45bbb4e',
    messagingSenderId: '904029642955',
    projectId: 'flutter-htl',
    authDomain: 'flutter-htl.firebaseapp.com',
    storageBucket: 'flutter-htl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM7Zx9J5KU0jay2E3DrOQw0EC43EoSHOA',
    appId: '1:904029642955:android:efbb7ae213af1bd75bbb4e',
    messagingSenderId: '904029642955',
    projectId: 'flutter-htl',
    storageBucket: 'flutter-htl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKDzDi4zX_x-1FgV6XZNu4UoOe8APxUE4',
    appId: '1:904029642955:ios:992f5033b2fa635b5bbb4e',
    messagingSenderId: '904029642955',
    projectId: 'flutter-htl',
    storageBucket: 'flutter-htl.appspot.com',
    iosClientId: '904029642955-7rdc7hl8fkv2kh3uh8nsi97pujme1l4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHtl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKDzDi4zX_x-1FgV6XZNu4UoOe8APxUE4',
    appId: '1:904029642955:ios:992f5033b2fa635b5bbb4e',
    messagingSenderId: '904029642955',
    projectId: 'flutter-htl',
    storageBucket: 'flutter-htl.appspot.com',
    iosClientId: '904029642955-7rdc7hl8fkv2kh3uh8nsi97pujme1l4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHtl',
  );
}
